apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
  namespace: mlflow
  labels:
    app: mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
      - name: mlflow
        image: python:3.9-slim
        ports:
        - containerPort: 5000
        env:
        - name: MLFLOW_BACKEND_STORE_URI
          value: "postgresql://mlflow:PASSWORD@DB_HOST:5432/mlflowdb"
        - name: MLFLOW_DEFAULT_ARTIFACT_ROOT
          value: "/tmp/mlflow"
        command:
        - /bin/bash
        - -c
        - |
          pip install mlflow[extras] psycopg2-binary
          mlflow server \
            --backend-store-uri $MLFLOW_BACKEND_STORE_URI \
            --default-artifact-root $MLFLOW_DEFAULT_ARTIFACT_ROOT \
            --host 0.0.0.0 \
            --port 5000
        volumeMounts:
        - name: mlflow-storage
          mountPath: /tmp/mlflow
      volumes:
      - name: mlflow-storage
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: mlflow
  namespace: mlflow
  labels:
    app: mlflow
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
  selector:
    app: mlflow
---
apiVersion: v1
kind: Namespace
metadata:
  name: mlflow 