name: MLOps CI - Build and Trigger SageMaker Pipeline

on:
  workflow_dispatch:

jobs:
  build-and-run-pipeline:
    runs-on: ubuntu-latest
    
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.GITHUB_ACTIONS_ROLE_ARN }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sagemaker boto3

    - name: Run SageMaker Pipeline
      run: python pipelines/abalone/run.py
      env:
        SAGEMAKER_ROLE_ARN: ${{ secrets.SAGEMAKER_ROLE_ARN }}
        S3_BUCKET: ${{ secrets.S3_BUCKET_NAME }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        DB_ENDPOINT: ${{ secrets.DB_ENDPOINT }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }} 