name: MLOps CD - Deploy Approved Model

on:
  repository_dispatch:
    types: [model-approved]

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    outputs:
      model_package_arn: ${{ github.event.client_payload.model_package_arn }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::<<AWS_ACCOUNT_ID>>:role/GitHubActionRole
        aws-region: <<AWS_REGION>>

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install boto3

    - name: Deploy to Staging
      run: |
        python scripts/deploy.py \
          --model-package-arn ${{ github.event.client_payload.model_package_arn }} \
          --environment staging
      env:
        AWS_REGION: <<AWS_REGION>>
        SAGEMAKER_ROLE_ARN: <<YOUR_SAGEMAKER_ROLE_ARN>>

  build-and-push-api:
    runs-on: ubuntu-latest
    needs: deploy-staging # Depends on getting the ARN, but can run in parallel
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::<<AWS_ACCOUNT_ID>>:role/GitHubActionRole
        aws-region: <<AWS_REGION>>

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: abalone-prediction-api
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./api
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

  test-staging:
    runs-on: ubuntu-latest
    needs: deploy-staging
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::<<AWS_ACCOUNT_ID>>:role/GitHubActionRole
        aws-region: <<AWS_REGION>>

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install boto3 requests

    - name: Test Staging Endpoint
      run: |
        # This is a simple test to check if the endpoint is invocable.
        # A more robust test would involve sending actual data and validating the prediction format/values.
        ENDPOINT_NAME="abalone-staging"
        REGION="<<AWS_REGION>>"
        PAYLOAD='5,0.455,0.365,0.095,0.514,0.2245,0.101,0.15' # Sample payload
        
        echo "Testing endpoint $ENDPOINT_NAME in region $REGION..."
        aws sagemaker-runtime invoke-endpoint \
          --endpoint-name $ENDPOINT_NAME \
          --region $REGION \
          --content-type "text/csv" \
          --body "$PAYLOAD" \
          /dev/stdout
        
        echo "Staging endpoint test completed."

  deploy-production:
    runs-on: ubuntu-latest
    needs: [test-staging, build-and-push-api]
    environment:
      name: production
      url: 'https://console.aws.amazon.com/sagemaker/home?region=<<AWS_REGION>>#/endpoints/abalone-production'
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::<<AWS_ACCOUNT_ID>>:role/GitHubActionRole
        aws-region: <<AWS_REGION>>
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install boto3

    - name: Deploy to Production via CloudFormation
      run: |
        python scripts/deploy.py \
          --model-package-arn ${{ needs.deploy-staging.outputs.model_package_arn }} \
          --environment production
      env:
        AWS_REGION: <<AWS_REGION>> 