name: 'Terraform - Provision or Update Infrastructure'

on:
  workflow_dispatch:

jobs:
  terraform:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.TERRAFORM_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.TERRAFORM_AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.2.9

    - name: Terraform Init
      run: |
        terraform init \
          -backend-config="bucket=${{ secrets.S3_BUCKET_NAME }}" \
          -backend-config="key=terraform.tfstate" \
          -backend-config="region=${{ secrets.AWS_REGION }}"
      working-directory: ./infrastructure

    - name: Terraform Plan
      run: terraform plan -var="aws_region=${{ secrets.AWS_REGION }}" -var="github_pat=${{ secrets.GH_PAT }}" -var="github_repo=${{ secrets.GH_REPO }}" -var="oidc_provider_arn=${{ secrets.OIDC_PROVIDER_ARN }}" -var="s3_bucket_name=${{ secrets.S3_BUCKET_NAME }}" -out=tfplan
      working-directory: ./infrastructure

    - name: Terraform Apply
      run: terraform apply -auto-approve tfplan
      working-directory: ./infrastructure 