name: Infrastructure Pipeline

on:
  workflow_dispatch:

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  terraform:
    name: 'Terraform Infrastructure'
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.5.0
        terraform_wrapper: false

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.TERRAFORM_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.TERRAFORM_AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Terraform Init
      working-directory: ./infrastructure
      run: |
        terraform init \
          -backend-config="bucket=${{ secrets.S3_BUCKET_NAME }}" \
          -backend-config="key=terraform.tfstate" \
          -backend-config="region=${{ secrets.AWS_REGION }}"

    - name: Terraform Plan
      working-directory: ./infrastructure
      run: |
        terraform plan \
          -var="aws_region=${{ secrets.AWS_REGION }}" \
          -var="s3_bucket_name=${{ secrets.S3_BUCKET_NAME }}" \
          -var="github_repo=${{ github.repository }}" \
          -var="github_pat=${{ secrets.GH_PAT }}" \
          -var="oidc_provider_arn=${{ secrets.OIDC_PROVIDER_ARN }}" \
          -out=tfplan

    - name: Terraform Apply
      working-directory: ./infrastructure
      run: terraform apply -auto-approve tfplan

    - name: Output Infrastructure Details
      working-directory: ./infrastructure
      run: |
        echo "🎉 Infrastructure deployment completed successfully!"
        echo ""
        echo "📋 Infrastructure Outputs:"
        echo "=========================="
        terraform output
        echo ""
        echo "✅ Next Steps:"
        echo "1. Copy the outputs above"
        echo "2. Add ECR repository URLs to GitHub Secrets"
        echo "3. Run 'Deploy MLflow to EKS' workflow"
        echo "4. Run ML Pipeline workflow to train models" 